version: "3.7"
services:
  web_portal:
    image: nginx:alpine
    container_name: web_portal
    volumes:
      - ./dist:/usr/share/nginx/html
      - ../default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5050:3000"
